### PR TITLE
Add basic tempvoice functionality

### PR DESCRIPTION
**Pull request by spr1t3-0**
Creation of voice channels is working, deletion after it's empty not. Can't create a new branch, this is not meant to be merged into main now.

### CODE REVIEW

**Comment by spr1t3-0** [comment]
The bot doesn't move a user to the newly created channel. Instead, they have to join on their own. If their channel is empty while another person enters the "magic voice channel" (where one joins to create a temproom), it gets deleted.

**Comment by LunaUrsa** [comment]
It shouldn't be hard to move the user from the hub into the temp room? Consider we have a lot of people on drugs, i think it should push them automatically

**Comment by spr1t3-0** [comment]
Done :)

**Review by LunaUrsa — APPROVED** [review]
Great work!

**Pull request merged**
